### ISSUE TITLE
Console.log not working and then() or catch() methods not called

### ISSUE THREAD

**Issue by darkyelox** [m-abs/nativescript-tslib#1]
When i apply this library into my NativesScript 3.4 version the project compiles and run but i dont see any console log and also the then or catch method are not called or simply i can't see logs.

**Comment by m-abs** [comment]
Hi @darkyelox 

Sorry I haven't responded untill now, I completely missed your issue.

Is this still an issue with nativescript 4.1?

**Comment by m-abs** [comment]
Closing this issue.
The plugin is deprecated and will no longer be updated.
